esd:
  port:
    http:
      host: 0.0.0.0
      port: 8089
      sock_type: 1
      open_http_protocol: true
scan:
  include_paths:
    examples: ${ROOT_DIR}/exampleClass
redis:
  default:
    host: 'redis-master.dev.svc.cluster.local'